name: WebSocketServices
main: com.caffeinatedrat.WebSocketServices.WebSocketServices
authors: ['CaffeinatedRat']
version: 1.0.2
description: Provides a simple websocket services for a Minecraft server.